### ISSUE TITLE
User cannot figure out how to open channel windows

### ISSUE THREAD

**Issue by hareesh-blippar** [Raptor-Fics-Interface/Raptor#45]
I've been using Raptor for a week (OS X), but I still do not know how to open a channel window, or a private chat window. There is no option to do so from the menus either. The UI needs improvement.

**Comment by cday-fics** [comment]
I disagree with you here too Raptor does not have private chat windows by design. If you want a private chat tab you can have it in many different forms. This will not be added in and is not a UI improvement needed.

**Comment by hareesh-blippar** [comment]
What about channel windows though?

**Comment by cday-fics** [comment]
There are no pop out windows only tabs and if you look around there are about 3 very easy ways to open them that are quite intuitive.

- Type +tab 1
- right click on a tell in a channel and select ADD CHANNEL TAB
- open up preferences ,select chat consoles, and select open channel tabs on new tell

Furthermore you can do this for person tell tabs, kibs/whispers during a game, etc.

Raptor will NEVER have pop out windows. Sometimes i think I should have named Raptor THIS INTERFACE IS NOT BABAS CHESS instead of Raptor. I hate the late 90s style of cramming every conceivable option or feature into an interface, cluttering it up, and taking away from its job which is TO PLAY CHESS! If you want this added in fork the project and add pop up windows.
