### ISSUE TITLE
Updated to OS sierra 10.12 and Raptor fails to start

### ISSUE THREAD

**Issue by cbdb85** [Raptor-Fics-Interface/Raptor#81]
Hey all

Recently updated my operating system to the OS sierra 10.12. When I click on Raptor I receive a notification box "to use the "java" command-line tool you need to install a JDK." I followed the prompts and installed the Java software. I still receive the same notification. 

any ideas?

thanks

**Comment by rjbriggs23** [comment]
I have the same issue.  I downloaded and installed the JDK as well--no go.  I then reinstalled Raptor.  Still no help.  Would love to see this resolved.

**Comment by rjbriggs23** [comment]
Made some progress, but still stuck.  I figured out that Java wasn't properly installing: terminal couldn't find it.  After some time on stackoverflow, I found and used homebrew to install java.  Now at terminal prompt: 

java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode

Unfortunately, now when I try to launch Raptor it straight crashes.  I can install an earlier version of Java if needed... what is the last version where Raptor is stable, or should it work on 10.0.2 and something else is wrong?

**Comment by carson-day** [comment]
Found the fix for this. It happens in java10+. This works in java12 (java10 is already EOL).
If you cd into Raptor.app from terminal you can edit the script that starts Raptor up to fix it. The problem has to do with an old flag no longer supported (-d64)
 
1) Edit Raptor.app/Contents/MacOS/raptor
2) Remove the line -d64 (This is no longer supported).
3) Double click on Raptor.app

Here is the file with -d64 removed:
#!/bin/sh
BASEDIR=`dirname $0`
cd $BASEDIR
exec java \
-XstartOnFirstThread \
-Xdock:icon=../Resources/Raptor.icns \
-Xms40m \
-Xmx100m \
-XX:MaxPermSize=128m \
-classpath $BASEDIR:$BASEDIR/Raptor.jar:$BASEDIR/swt/swt.jar:$BASEDIR/common/bsh-2.0b4.jar:$BASEDIR/common/commons-collections-3.2.1.jar:$BASEDIR/common/commons-configuration-1.6.jar:$BASEDIR/common/commons-lang-2.4.jar:$BASEDIR/common/commons-logging-1.1.1.jar:$BASEDIR/common/junit4_4.3.1.jar:$BASEDIR/common/log4j-1.2.15.jar:$BASEDIR/common/org.eclipse.core.commands_3.4.0.I20080509-2000.jar:$BASEDIR/common/org.eclipse.equinox.common_3.4.0.v20080421-2006.jar:$BASEDIR/common/org.eclipse.jface_3.4.2.M20090107-0800.jar:$BASEDIR/common/org.eclipse.jface.text_3.4.2.r342_v20081119-0800.jar:$BASEDIR/common/org.eclipse.osgi_3.4.3.R34x_v20081215-1030.jar \
raptor.Raptor

**Comment by rjbriggs23** [comment]
Awesome.  Thanks for this.  I’ll give it a shot :D  If it works, you won’t hear further from me on the issue ;)

-R. J.
